MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "11.0"                 # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "11.0"                 # [osx and x86_64]
libevent:
  - "2.1.10"
lmdb:
  - "0.9.22"
folly:
  # This version of folly is used to make the build usable by more environments
  - "2023.09.25.00"
