MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "11.0"                 # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "11.0"                 # [osx and x86_64]
libevent:
  - "2.1.10"
  - "2.1.12"
lmdb:
  - 0.9.22
aws_sdk_cpp:
  - 1.10.57
