MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "11.0"                 # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "11.0"                 # [osx and x86_64]
lmdb:
  - 0.9.22
nodejs:
  - "18"
protobuf:
  - "<4"
  - "*"
